// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mocks.go -source ./interface.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	provider "github.com/stiflerGit/moviehat/internal/movie/provider"
	gomock "go.uber.org/mock/gomock"
)

// MockMoviesSearcher is a mock of MoviesSearcher interface.
type MockMoviesSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesSearcherMockRecorder
	isgomock struct{}
}

// MockMoviesSearcherMockRecorder is the mock recorder for MockMoviesSearcher.
type MockMoviesSearcherMockRecorder struct {
	mock *MockMoviesSearcher
}

// NewMockMoviesSearcher creates a new mock instance.
func NewMockMoviesSearcher(ctrl *gomock.Controller) *MockMoviesSearcher {
	mock := &MockMoviesSearcher{ctrl: ctrl}
	mock.recorder = &MockMoviesSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesSearcher) EXPECT() *MockMoviesSearcherMockRecorder {
	return m.recorder
}

// SearchMovies mocks base method.
func (m *MockMoviesSearcher) SearchMovies(ctx context.Context, arg provider.SearchMoviesArg) (provider.SearchMoviesRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", ctx, arg)
	ret0, _ := ret[0].(provider.SearchMoviesRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockMoviesSearcherMockRecorder) SearchMovies(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockMoviesSearcher)(nil).SearchMovies), ctx, arg)
}

// MockMovieDetailsGetter is a mock of MovieDetailsGetter interface.
type MockMovieDetailsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMovieDetailsGetterMockRecorder
	isgomock struct{}
}

// MockMovieDetailsGetterMockRecorder is the mock recorder for MockMovieDetailsGetter.
type MockMovieDetailsGetterMockRecorder struct {
	mock *MockMovieDetailsGetter
}

// NewMockMovieDetailsGetter creates a new mock instance.
func NewMockMovieDetailsGetter(ctrl *gomock.Controller) *MockMovieDetailsGetter {
	mock := &MockMovieDetailsGetter{ctrl: ctrl}
	mock.recorder = &MockMovieDetailsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieDetailsGetter) EXPECT() *MockMovieDetailsGetterMockRecorder {
	return m.recorder
}

// GetDetails mocks base method.
func (m *MockMovieDetailsGetter) GetDetails(ctx context.Context, arg provider.GetDetailsArg) (provider.GetDetailsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, arg)
	ret0, _ := ret[0].(provider.GetDetailsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockMovieDetailsGetterMockRecorder) GetDetails(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockMovieDetailsGetter)(nil).GetDetails), ctx, arg)
}
