// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/core (interfaces: MovieSearchEngine)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/movie_search_engine.go . MovieSearchEngine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gatewayv1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieSearchEngine is a mock of MovieSearchEngine interface.
type MockMovieSearchEngine struct {
	ctrl     *gomock.Controller
	recorder *MockMovieSearchEngineMockRecorder
	isgomock struct{}
}

// MockMovieSearchEngineMockRecorder is the mock recorder for MockMovieSearchEngine.
type MockMovieSearchEngineMockRecorder struct {
	mock *MockMovieSearchEngine
}

// NewMockMovieSearchEngine creates a new mock instance.
func NewMockMovieSearchEngine(ctrl *gomock.Controller) *MockMovieSearchEngine {
	mock := &MockMovieSearchEngine{ctrl: ctrl}
	mock.recorder = &MockMovieSearchEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieSearchEngine) EXPECT() *MockMovieSearchEngineMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMovieSearchEngine) GetByID(ctx context.Context, id string) (*gatewayv1.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*gatewayv1.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMovieSearchEngineMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMovieSearchEngine)(nil).GetByID), ctx, id)
}

// Search mocks base method.
func (m *MockMovieSearchEngine) Search(arg0 context.Context, arg1 *gatewayv1.SearchMovieRequest) (*gatewayv1.SearchMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.SearchMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockMovieSearchEngineMockRecorder) Search(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockMovieSearchEngine)(nil).Search), arg0, arg1)
}
