// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/store.go -source ./types.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	persistence "github.com/stiflerGit/moviehat/internal/lottery/weighted/scorer/fair_share/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionalStorage is a mock of TransactionalStorage interface.
type MockTransactionalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalStorageMockRecorder
	isgomock struct{}
}

// MockTransactionalStorageMockRecorder is the mock recorder for MockTransactionalStorage.
type MockTransactionalStorageMockRecorder struct {
	mock *MockTransactionalStorage
}

// NewMockTransactionalStorage creates a new mock instance.
func NewMockTransactionalStorage(ctrl *gomock.Controller) *MockTransactionalStorage {
	mock := &MockTransactionalStorage{ctrl: ctrl}
	mock.recorder = &MockTransactionalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalStorage) EXPECT() *MockTransactionalStorageMockRecorder {
	return m.recorder
}

// IncreaseUserScore mocks base method.
func (m *MockTransactionalStorage) IncreaseUserScore(ctx context.Context, in persistence.IncreaseUserScoreArg) (persistence.IncreaseUserScoreRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseUserScore", ctx, in)
	ret0, _ := ret[0].(persistence.IncreaseUserScoreRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseUserScore indicates an expected call of IncreaseUserScore.
func (mr *MockTransactionalStorageMockRecorder) IncreaseUserScore(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseUserScore", reflect.TypeOf((*MockTransactionalStorage)(nil).IncreaseUserScore), ctx, in)
}

// ListUsersScores mocks base method.
func (m *MockTransactionalStorage) ListUsersScores(ctx context.Context, arg persistence.ListUsersScoresArg) (persistence.ListUsersScoresRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersScores", ctx, arg)
	ret0, _ := ret[0].(persistence.ListUsersScoresRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersScores indicates an expected call of ListUsersScores.
func (mr *MockTransactionalStorageMockRecorder) ListUsersScores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersScores", reflect.TypeOf((*MockTransactionalStorage)(nil).ListUsersScores), ctx, arg)
}

// WithTx mocks base method.
func (m *MockTransactionalStorage) WithTx(ctx context.Context, fn func(context.Context, persistence.Storage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactionalStorageMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactionalStorage)(nil).WithTx), ctx, fn)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// IncreaseUserScore mocks base method.
func (m *MockStorage) IncreaseUserScore(ctx context.Context, in persistence.IncreaseUserScoreArg) (persistence.IncreaseUserScoreRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseUserScore", ctx, in)
	ret0, _ := ret[0].(persistence.IncreaseUserScoreRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseUserScore indicates an expected call of IncreaseUserScore.
func (mr *MockStorageMockRecorder) IncreaseUserScore(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseUserScore", reflect.TypeOf((*MockStorage)(nil).IncreaseUserScore), ctx, in)
}

// ListUsersScores mocks base method.
func (m *MockStorage) ListUsersScores(ctx context.Context, arg persistence.ListUsersScoresArg) (persistence.ListUsersScoresRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersScores", ctx, arg)
	ret0, _ := ret[0].(persistence.ListUsersScoresRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersScores indicates an expected call of ListUsersScores.
func (mr *MockStorageMockRecorder) ListUsersScores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersScores", reflect.TypeOf((*MockStorage)(nil).ListUsersScores), ctx, arg)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTransactor) WithTx(ctx context.Context, fn func(context.Context, persistence.Storage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactorMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactor)(nil).WithTx), ctx, fn)
}
