// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/gateway/v1 (interfaces: AuthHandler)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/auth_handler.go . AuthHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gatewayv1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	auth "github.com/stiflerGit/moviehat/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandler is a mock of AuthHandler interface.
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
	isgomock struct{}
}

// MockAuthHandlerMockRecorder is the mock recorder for MockAuthHandler.
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler creates a new mock instance.
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// CreateInvitation mocks base method.
func (m *MockAuthHandler) CreateInvitation(arg0 context.Context, arg1 *gatewayv1.CreateInvitationRequest) (*gatewayv1.CreateInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.CreateInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockAuthHandlerMockRecorder) CreateInvitation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockAuthHandler)(nil).CreateInvitation), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockAuthHandler) DeleteUser(ctx context.Context, req *gatewayv1.DeleteUserRequest) (*gatewayv1.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAuthHandlerMockRecorder) DeleteUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAuthHandler)(nil).DeleteUser), ctx, req)
}

// SignIn mocks base method.
func (m *MockAuthHandler) SignIn(ctx context.Context, req *gatewayv1.SignInRequest) (*gatewayv1.SignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.SignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthHandlerMockRecorder) SignIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthHandler)(nil).SignIn), ctx, req)
}

// SignOut mocks base method.
func (m *MockAuthHandler) SignOut(ctx context.Context, req *gatewayv1.SignOutRequest) (*gatewayv1.SignOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.SignOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignOut indicates an expected call of SignOut.
func (mr *MockAuthHandlerMockRecorder) SignOut(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockAuthHandler)(nil).SignOut), ctx, req)
}

// SignUp mocks base method.
func (m *MockAuthHandler) SignUp(ctx context.Context, req *gatewayv1.SignUpRequest) (auth.SignUpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, req)
	ret0, _ := ret[0].(auth.SignUpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthHandlerMockRecorder) SignUp(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthHandler)(nil).SignUp), ctx, req)
}
