// Code generated by MockGen. DO NOT EDIT.
// Source: ./gateway.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mocks.go -source=./gateway.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gatewayv1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	auth "github.com/stiflerGit/moviehat/internal/auth"
	list "github.com/stiflerGit/moviehat/internal/list"
	session "github.com/stiflerGit/moviehat/internal/session"
	user "github.com/stiflerGit/moviehat/internal/user"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandler is a mock of AuthHandler interface.
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
	isgomock struct{}
}

// MockAuthHandlerMockRecorder is the mock recorder for MockAuthHandler.
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler creates a new mock instance.
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// CreateInvitation mocks base method.
func (m *MockAuthHandler) CreateInvitation(arg0 context.Context, arg1 *gatewayv1.CreateInvitationRequest) (*gatewayv1.CreateInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.CreateInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockAuthHandlerMockRecorder) CreateInvitation(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockAuthHandler)(nil).CreateInvitation), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockAuthHandler) DeleteUser(ctx context.Context, req *gatewayv1.DeleteUserRequest) (*gatewayv1.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAuthHandlerMockRecorder) DeleteUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAuthHandler)(nil).DeleteUser), ctx, req)
}

// SignIn mocks base method.
func (m *MockAuthHandler) SignIn(ctx context.Context, req *gatewayv1.SignInRequest) (*gatewayv1.SignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.SignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockAuthHandlerMockRecorder) SignIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockAuthHandler)(nil).SignIn), ctx, req)
}

// SignOut mocks base method.
func (m *MockAuthHandler) SignOut(ctx context.Context, req *gatewayv1.SignOutRequest) (*gatewayv1.SignOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOut", ctx, req)
	ret0, _ := ret[0].(*gatewayv1.SignOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignOut indicates an expected call of SignOut.
func (mr *MockAuthHandlerMockRecorder) SignOut(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOut", reflect.TypeOf((*MockAuthHandler)(nil).SignOut), ctx, req)
}

// SignUp mocks base method.
func (m *MockAuthHandler) SignUp(ctx context.Context, req *gatewayv1.SignUpRequest) (auth.SignUpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, req)
	ret0, _ := ret[0].(auth.SignUpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockAuthHandlerMockRecorder) SignUp(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockAuthHandler)(nil).SignUp), ctx, req)
}

// MockUsersHandler is a mock of UsersHandler interface.
type MockUsersHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUsersHandlerMockRecorder
	isgomock struct{}
}

// MockUsersHandlerMockRecorder is the mock recorder for MockUsersHandler.
type MockUsersHandlerMockRecorder struct {
	mock *MockUsersHandler
}

// NewMockUsersHandler creates a new mock instance.
func NewMockUsersHandler(ctrl *gomock.Controller) *MockUsersHandler {
	mock := &MockUsersHandler{ctrl: ctrl}
	mock.recorder = &MockUsersHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersHandler) EXPECT() *MockUsersHandlerMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersHandler) CreateUser(arg0 context.Context, arg1 user.CreateUserRequest) (user.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(user.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersHandlerMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersHandler)(nil).CreateUser), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockUsersHandler) DeleteUser(arg0 context.Context, arg1 user.DeleteUserRequest) (*gatewayv1.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersHandlerMockRecorder) DeleteUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersHandler)(nil).DeleteUser), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockUsersHandler) ListUsers(arg0 context.Context, arg1 *gatewayv1.ListUsersRequest) (*gatewayv1.ListUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUsersHandlerMockRecorder) ListUsers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUsersHandler)(nil).ListUsers), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockUsersHandler) UpdateUser(arg0 context.Context, arg1 user.UpdateUserRequest) (*gatewayv1.UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersHandlerMockRecorder) UpdateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersHandler)(nil).UpdateUser), arg0, arg1)
}

// MockSessionsHandler is a mock of SessionsHandler interface.
type MockSessionsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSessionsHandlerMockRecorder
	isgomock struct{}
}

// MockSessionsHandlerMockRecorder is the mock recorder for MockSessionsHandler.
type MockSessionsHandlerMockRecorder struct {
	mock *MockSessionsHandler
}

// NewMockSessionsHandler creates a new mock instance.
func NewMockSessionsHandler(ctrl *gomock.Controller) *MockSessionsHandler {
	mock := &MockSessionsHandler{ctrl: ctrl}
	mock.recorder = &MockSessionsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionsHandler) EXPECT() *MockSessionsHandlerMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockSessionsHandler) AddParticipant(arg0 context.Context, arg1 *gatewayv1.AddParticipantRequest) (*gatewayv1.AddParticipantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.AddParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockSessionsHandlerMockRecorder) AddParticipant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockSessionsHandler)(nil).AddParticipant), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockSessionsHandler) CreateSession(arg0 context.Context, arg1 *gatewayv1.CreateSessionRequest) (*gatewayv1.CreateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.CreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionsHandlerMockRecorder) CreateSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionsHandler)(nil).CreateSession), arg0, arg1)
}

// DeleteSession mocks base method.
func (m *MockSessionsHandler) DeleteSession(arg0 context.Context, arg1 *gatewayv1.DeleteSessionRequest) (*gatewayv1.DeleteSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionsHandlerMockRecorder) DeleteSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionsHandler)(nil).DeleteSession), arg0, arg1)
}

// EndSession mocks base method.
func (m *MockSessionsHandler) EndSession(arg0 context.Context, arg1 *gatewayv1.EndSessionRequest) (*gatewayv1.EndSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.EndSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndSession indicates an expected call of EndSession.
func (mr *MockSessionsHandlerMockRecorder) EndSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSession", reflect.TypeOf((*MockSessionsHandler)(nil).EndSession), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockSessionsHandler) GetSession(arg0 context.Context, arg1 *gatewayv1.GetSessionRequest) (*gatewayv1.GetSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.GetSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionsHandlerMockRecorder) GetSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionsHandler)(nil).GetSession), arg0, arg1)
}

// GetSessionProbabilities mocks base method.
func (m *MockSessionsHandler) GetSessionProbabilities(arg0 context.Context, arg1 *gatewayv1.GetSessionProbabilitiesRequest) (*gatewayv1.GetSessionProbabilitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionProbabilities", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.GetSessionProbabilitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionProbabilities indicates an expected call of GetSessionProbabilities.
func (mr *MockSessionsHandlerMockRecorder) GetSessionProbabilities(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionProbabilities", reflect.TypeOf((*MockSessionsHandler)(nil).GetSessionProbabilities), arg0, arg1)
}

// ListParticipants mocks base method.
func (m *MockSessionsHandler) ListParticipants(arg0 context.Context, arg1 *gatewayv1.ListParticipantsRequest) (*gatewayv1.ListParticipantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListParticipantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockSessionsHandlerMockRecorder) ListParticipants(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockSessionsHandler)(nil).ListParticipants), arg0, arg1)
}

// ListSessions mocks base method.
func (m *MockSessionsHandler) ListSessions(arg0 context.Context, arg1 *gatewayv1.ListSessionsRequest) (*gatewayv1.ListSessionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListSessionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockSessionsHandlerMockRecorder) ListSessions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockSessionsHandler)(nil).ListSessions), arg0, arg1)
}

// RemoveParticipant mocks base method.
func (m *MockSessionsHandler) RemoveParticipant(arg0 context.Context, arg1 *gatewayv1.RemoveParticipantRequest) (*gatewayv1.RemoveParticipantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.RemoveParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockSessionsHandlerMockRecorder) RemoveParticipant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockSessionsHandler)(nil).RemoveParticipant), arg0, arg1)
}

// SetSessionMovie mocks base method.
func (m *MockSessionsHandler) SetSessionMovie(arg0 context.Context, arg1 session.SetSessionMovieRequest) (*gatewayv1.SetSessionMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.SetSessionMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionMovie indicates an expected call of SetSessionMovie.
func (mr *MockSessionsHandlerMockRecorder) SetSessionMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionMovie", reflect.TypeOf((*MockSessionsHandler)(nil).SetSessionMovie), arg0, arg1)
}

// MockListsHandler is a mock of ListsHandler interface.
type MockListsHandler struct {
	ctrl     *gomock.Controller
	recorder *MockListsHandlerMockRecorder
	isgomock struct{}
}

// MockListsHandlerMockRecorder is the mock recorder for MockListsHandler.
type MockListsHandlerMockRecorder struct {
	mock *MockListsHandler
}

// NewMockListsHandler creates a new mock instance.
func NewMockListsHandler(ctrl *gomock.Controller) *MockListsHandler {
	mock := &MockListsHandler{ctrl: ctrl}
	mock.recorder = &MockListsHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListsHandler) EXPECT() *MockListsHandlerMockRecorder {
	return m.recorder
}

// AddUserMovie mocks base method.
func (m *MockListsHandler) AddUserMovie(arg0 context.Context, arg1 list.AddUserMovieRequest) (*gatewayv1.AddUserMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.AddUserMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserMovie indicates an expected call of AddUserMovie.
func (mr *MockListsHandlerMockRecorder) AddUserMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserMovie", reflect.TypeOf((*MockListsHandler)(nil).AddUserMovie), arg0, arg1)
}

// DeleteUserMovie mocks base method.
func (m *MockListsHandler) DeleteUserMovie(arg0 context.Context, arg1 list.DeleteUserMovieRequest) (*gatewayv1.DeleteUserMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserMovie indicates an expected call of DeleteUserMovie.
func (mr *MockListsHandlerMockRecorder) DeleteUserMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserMovie", reflect.TypeOf((*MockListsHandler)(nil).DeleteUserMovie), arg0, arg1)
}

// ListUserMovies mocks base method.
func (m *MockListsHandler) ListUserMovies(arg0 context.Context, arg1 *gatewayv1.ListUserMoviesRequest) (*gatewayv1.ListUserMoviesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserMovies", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListUserMoviesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserMovies indicates an expected call of ListUserMovies.
func (mr *MockListsHandlerMockRecorder) ListUserMovies(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserMovies", reflect.TypeOf((*MockListsHandler)(nil).ListUserMovies), arg0, arg1)
}

// MockMovieHandler is a mock of MovieHandler interface.
type MockMovieHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMovieHandlerMockRecorder
	isgomock struct{}
}

// MockMovieHandlerMockRecorder is the mock recorder for MockMovieHandler.
type MockMovieHandlerMockRecorder struct {
	mock *MockMovieHandler
}

// NewMockMovieHandler creates a new mock instance.
func NewMockMovieHandler(ctrl *gomock.Controller) *MockMovieHandler {
	mock := &MockMovieHandler{ctrl: ctrl}
	mock.recorder = &MockMovieHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieHandler) EXPECT() *MockMovieHandlerMockRecorder {
	return m.recorder
}

// SearchMovie mocks base method.
func (m *MockMovieHandler) SearchMovie(arg0 context.Context, arg1 *gatewayv1.SearchMovieRequest) (*gatewayv1.SearchMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.SearchMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovie indicates an expected call of SearchMovie.
func (mr *MockMovieHandlerMockRecorder) SearchMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovie", reflect.TypeOf((*MockMovieHandler)(nil).SearchMovie), arg0, arg1)
}
