// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/gateway/v1 (interfaces: MovieHatHandler)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/moviehat_handler.go . MovieHatHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gatewayv1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	v1 "github.com/stiflerGit/moviehat/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieHatHandler is a mock of MovieHatHandler interface.
type MockMovieHatHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMovieHatHandlerMockRecorder
	isgomock struct{}
}

// MockMovieHatHandlerMockRecorder is the mock recorder for MockMovieHatHandler.
type MockMovieHatHandlerMockRecorder struct {
	mock *MockMovieHatHandler
}

// NewMockMovieHatHandler creates a new mock instance.
func NewMockMovieHatHandler(ctrl *gomock.Controller) *MockMovieHatHandler {
	mock := &MockMovieHatHandler{ctrl: ctrl}
	mock.recorder = &MockMovieHatHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieHatHandler) EXPECT() *MockMovieHatHandlerMockRecorder {
	return m.recorder
}

// AddParticipant mocks base method.
func (m *MockMovieHatHandler) AddParticipant(arg0 context.Context, arg1 *gatewayv1.AddParticipantRequest) (*gatewayv1.AddParticipantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddParticipant", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.AddParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddParticipant indicates an expected call of AddParticipant.
func (mr *MockMovieHatHandlerMockRecorder) AddParticipant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddParticipant", reflect.TypeOf((*MockMovieHatHandler)(nil).AddParticipant), arg0, arg1)
}

// AddUserMovie mocks base method.
func (m *MockMovieHatHandler) AddUserMovie(arg0 context.Context, arg1 *gatewayv1.AddUserMovieRequest) (*gatewayv1.AddUserMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.AddUserMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserMovie indicates an expected call of AddUserMovie.
func (mr *MockMovieHatHandlerMockRecorder) AddUserMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserMovie", reflect.TypeOf((*MockMovieHatHandler)(nil).AddUserMovie), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockMovieHatHandler) CreateSession(arg0 context.Context, arg1 *gatewayv1.CreateSessionRequest) (*gatewayv1.CreateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.CreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockMovieHatHandlerMockRecorder) CreateSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockMovieHatHandler)(nil).CreateSession), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockMovieHatHandler) CreateUser(arg0 context.Context, arg1 v1.CreateUserRequest) (v1.CreateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(v1.CreateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockMovieHatHandlerMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockMovieHatHandler)(nil).CreateUser), arg0, arg1)
}

// DeleteSession mocks base method.
func (m *MockMovieHatHandler) DeleteSession(arg0 context.Context, arg1 *gatewayv1.DeleteSessionRequest) (*gatewayv1.DeleteSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockMovieHatHandlerMockRecorder) DeleteSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockMovieHatHandler)(nil).DeleteSession), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockMovieHatHandler) DeleteUser(arg0 context.Context, arg1 *gatewayv1.DeleteUserRequest) (*gatewayv1.DeleteUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockMovieHatHandlerMockRecorder) DeleteUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockMovieHatHandler)(nil).DeleteUser), arg0, arg1)
}

// DeleteUserMovie mocks base method.
func (m *MockMovieHatHandler) DeleteUserMovie(arg0 context.Context, arg1 *gatewayv1.DeleteUserMovieRequest) (*gatewayv1.DeleteUserMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.DeleteUserMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserMovie indicates an expected call of DeleteUserMovie.
func (mr *MockMovieHatHandlerMockRecorder) DeleteUserMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserMovie", reflect.TypeOf((*MockMovieHatHandler)(nil).DeleteUserMovie), arg0, arg1)
}

// EndSession mocks base method.
func (m *MockMovieHatHandler) EndSession(arg0 context.Context, arg1 *gatewayv1.EndSessionRequest) (*gatewayv1.EndSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.EndSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndSession indicates an expected call of EndSession.
func (mr *MockMovieHatHandlerMockRecorder) EndSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSession", reflect.TypeOf((*MockMovieHatHandler)(nil).EndSession), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockMovieHatHandler) GetSession(arg0 context.Context, arg1 *gatewayv1.GetSessionRequest) (*gatewayv1.GetSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.GetSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockMovieHatHandlerMockRecorder) GetSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockMovieHatHandler)(nil).GetSession), arg0, arg1)
}

// GetSessionProbabilities mocks base method.
func (m *MockMovieHatHandler) GetSessionProbabilities(arg0 context.Context, arg1 *gatewayv1.GetSessionProbabilitiesRequest) (*gatewayv1.GetSessionProbabilitiesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionProbabilities", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.GetSessionProbabilitiesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionProbabilities indicates an expected call of GetSessionProbabilities.
func (mr *MockMovieHatHandlerMockRecorder) GetSessionProbabilities(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionProbabilities", reflect.TypeOf((*MockMovieHatHandler)(nil).GetSessionProbabilities), arg0, arg1)
}

// ListParticipants mocks base method.
func (m *MockMovieHatHandler) ListParticipants(arg0 context.Context, arg1 *gatewayv1.ListParticipantsRequest) (*gatewayv1.ListParticipantsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListParticipantsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockMovieHatHandlerMockRecorder) ListParticipants(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockMovieHatHandler)(nil).ListParticipants), arg0, arg1)
}

// ListSessions mocks base method.
func (m *MockMovieHatHandler) ListSessions(arg0 context.Context, arg1 *gatewayv1.ListSessionsRequest) (*gatewayv1.ListSessionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListSessionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockMovieHatHandlerMockRecorder) ListSessions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockMovieHatHandler)(nil).ListSessions), arg0, arg1)
}

// ListUserMovies mocks base method.
func (m *MockMovieHatHandler) ListUserMovies(arg0 context.Context, arg1 *gatewayv1.ListUserMoviesRequest) (*gatewayv1.ListUserMoviesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserMovies", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListUserMoviesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserMovies indicates an expected call of ListUserMovies.
func (mr *MockMovieHatHandlerMockRecorder) ListUserMovies(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserMovies", reflect.TypeOf((*MockMovieHatHandler)(nil).ListUserMovies), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockMovieHatHandler) ListUsers(arg0 context.Context, arg1 *gatewayv1.ListUsersRequest) (*gatewayv1.ListUsersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.ListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockMovieHatHandlerMockRecorder) ListUsers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockMovieHatHandler)(nil).ListUsers), arg0, arg1)
}

// RemoveParticipant mocks base method.
func (m *MockMovieHatHandler) RemoveParticipant(arg0 context.Context, arg1 *gatewayv1.RemoveParticipantRequest) (*gatewayv1.RemoveParticipantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveParticipant", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.RemoveParticipantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveParticipant indicates an expected call of RemoveParticipant.
func (mr *MockMovieHatHandlerMockRecorder) RemoveParticipant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveParticipant", reflect.TypeOf((*MockMovieHatHandler)(nil).RemoveParticipant), arg0, arg1)
}

// SearchMovie mocks base method.
func (m *MockMovieHatHandler) SearchMovie(arg0 context.Context, arg1 *gatewayv1.SearchMovieRequest) (*gatewayv1.SearchMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.SearchMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovie indicates an expected call of SearchMovie.
func (mr *MockMovieHatHandlerMockRecorder) SearchMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovie", reflect.TypeOf((*MockMovieHatHandler)(nil).SearchMovie), arg0, arg1)
}

// SetSessionMovie mocks base method.
func (m *MockMovieHatHandler) SetSessionMovie(arg0 context.Context, arg1 *gatewayv1.SetSessionMovieRequest) (*gatewayv1.SetSessionMovieResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionMovie", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.SetSessionMovieResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSessionMovie indicates an expected call of SetSessionMovie.
func (mr *MockMovieHatHandlerMockRecorder) SetSessionMovie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionMovie", reflect.TypeOf((*MockMovieHatHandler)(nil).SetSessionMovie), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockMovieHatHandler) UpdateUser(arg0 context.Context, arg1 *gatewayv1.UpdateUserRequest) (*gatewayv1.UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(*gatewayv1.UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockMovieHatHandlerMockRecorder) UpdateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockMovieHatHandler)(nil).UpdateUser), arg0, arg1)
}
