// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/auth/persistence (interfaces: TransactionalStorage)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/store.go . TransactionalStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	persistence "github.com/stiflerGit/moviehat/internal/auth/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionalStorage is a mock of TransactionalStorage interface.
type MockTransactionalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalStorageMockRecorder
	isgomock struct{}
}

// MockTransactionalStorageMockRecorder is the mock recorder for MockTransactionalStorage.
type MockTransactionalStorageMockRecorder struct {
	mock *MockTransactionalStorage
}

// NewMockTransactionalStorage creates a new mock instance.
func NewMockTransactionalStorage(ctrl *gomock.Controller) *MockTransactionalStorage {
	mock := &MockTransactionalStorage{ctrl: ctrl}
	mock.recorder = &MockTransactionalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalStorage) EXPECT() *MockTransactionalStorageMockRecorder {
	return m.recorder
}

// ConsumeVerification mocks base method.
func (m *MockTransactionalStorage) ConsumeVerification(ctx context.Context, in persistence.ConsumeVerificationArg) (persistence.ConsumeVerificationRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeVerification", ctx, in)
	ret0, _ := ret[0].(persistence.ConsumeVerificationRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeVerification indicates an expected call of ConsumeVerification.
func (mr *MockTransactionalStorageMockRecorder) ConsumeVerification(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeVerification", reflect.TypeOf((*MockTransactionalStorage)(nil).ConsumeVerification), ctx, in)
}

// DeleteUser mocks base method.
func (m *MockTransactionalStorage) DeleteUser(ctx context.Context, in persistence.DeleteUserArg) (persistence.DeleteUserRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, in)
	ret0, _ := ret[0].(persistence.DeleteUserRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockTransactionalStorageMockRecorder) DeleteUser(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockTransactionalStorage)(nil).DeleteUser), ctx, in)
}

// GetSession mocks base method.
func (m *MockTransactionalStorage) GetSession(ctx context.Context, in persistence.GetSessionArg) (persistence.GetSessionRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, in)
	ret0, _ := ret[0].(persistence.GetSessionRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockTransactionalStorageMockRecorder) GetSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockTransactionalStorage)(nil).GetSession), ctx, in)
}

// GetUser mocks base method.
func (m *MockTransactionalStorage) GetUser(ctx context.Context, in persistence.GetUserArg) (persistence.GetUserRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, in)
	ret0, _ := ret[0].(persistence.GetUserRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTransactionalStorageMockRecorder) GetUser(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTransactionalStorage)(nil).GetUser), ctx, in)
}

// GetVerification mocks base method.
func (m *MockTransactionalStorage) GetVerification(ctx context.Context, in persistence.GetVerificationArg) (persistence.GetVerificationRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerification", ctx, in)
	ret0, _ := ret[0].(persistence.GetVerificationRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerification indicates an expected call of GetVerification.
func (mr *MockTransactionalStorageMockRecorder) GetVerification(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerification", reflect.TypeOf((*MockTransactionalStorage)(nil).GetVerification), ctx, in)
}

// InsertSession mocks base method.
func (m *MockTransactionalStorage) InsertSession(ctx context.Context, in persistence.InsertSessionArg) (persistence.InsertSessionRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSession", ctx, in)
	ret0, _ := ret[0].(persistence.InsertSessionRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSession indicates an expected call of InsertSession.
func (mr *MockTransactionalStorageMockRecorder) InsertSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSession", reflect.TypeOf((*MockTransactionalStorage)(nil).InsertSession), ctx, in)
}

// InsertUser mocks base method.
func (m *MockTransactionalStorage) InsertUser(ctx context.Context, in persistence.InsertUserArg) (persistence.InsertUserRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", ctx, in)
	ret0, _ := ret[0].(persistence.InsertUserRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockTransactionalStorageMockRecorder) InsertUser(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockTransactionalStorage)(nil).InsertUser), ctx, in)
}

// InsertVerification mocks base method.
func (m *MockTransactionalStorage) InsertVerification(ctx context.Context, in persistence.InsertVerificationArg) (persistence.InsertVerificationRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVerification", ctx, in)
	ret0, _ := ret[0].(persistence.InsertVerificationRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertVerification indicates an expected call of InsertVerification.
func (mr *MockTransactionalStorageMockRecorder) InsertVerification(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVerification", reflect.TypeOf((*MockTransactionalStorage)(nil).InsertVerification), ctx, in)
}

// UpdateSession mocks base method.
func (m *MockTransactionalStorage) UpdateSession(ctx context.Context, in persistence.UpdateSessionArg) (persistence.UpdateSessionRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, in)
	ret0, _ := ret[0].(persistence.UpdateSessionRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockTransactionalStorageMockRecorder) UpdateSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockTransactionalStorage)(nil).UpdateSession), ctx, in)
}

// UpdateVerification mocks base method.
func (m *MockTransactionalStorage) UpdateVerification(ctx context.Context, in persistence.UpdateVerificationArg) (persistence.UpdateVerificationRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerification", ctx, in)
	ret0, _ := ret[0].(persistence.UpdateVerificationRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVerification indicates an expected call of UpdateVerification.
func (mr *MockTransactionalStorageMockRecorder) UpdateVerification(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerification", reflect.TypeOf((*MockTransactionalStorage)(nil).UpdateVerification), ctx, in)
}

// WithTx mocks base method.
func (m *MockTransactionalStorage) WithTx(ctx context.Context, fn func(context.Context, persistence.Storage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactionalStorageMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactionalStorage)(nil).WithTx), ctx, fn)
}
