// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mocks.go -source=handler.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	lottery "github.com/stiflerGit/moviehat/internal/lottery"
	persistence "github.com/stiflerGit/moviehat/internal/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockStorage) CloseSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockStorageMockRecorder) CloseSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockStorage)(nil).CloseSession), ctx, id)
}

// CreateParticipant mocks base method.
func (m *MockStorage) CreateParticipant(ctx context.Context, req persistence.CreateParticipantArg) (persistence.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParticipant", ctx, req)
	ret0, _ := ret[0].(persistence.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateParticipant indicates an expected call of CreateParticipant.
func (mr *MockStorageMockRecorder) CreateParticipant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParticipant", reflect.TypeOf((*MockStorage)(nil).CreateParticipant), ctx, req)
}

// CreateSession mocks base method.
func (m *MockStorage) CreateSession(ctx context.Context, req persistence.CreateSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStorageMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStorage)(nil).CreateSession), ctx, req)
}

// DeleteParticipant mocks base method.
func (m *MockStorage) DeleteParticipant(ctx context.Context, req persistence.DeleteParticipantArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParticipant", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParticipant indicates an expected call of DeleteParticipant.
func (mr *MockStorageMockRecorder) DeleteParticipant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipant", reflect.TypeOf((*MockStorage)(nil).DeleteParticipant), ctx, req)
}

// DeleteSession mocks base method.
func (m *MockStorage) DeleteSession(ctx context.Context, id string) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStorageMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStorage)(nil).DeleteSession), ctx, id)
}

// GetSession mocks base method.
func (m *MockStorage) GetSession(ctx context.Context, req persistence.GetSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStorageMockRecorder) GetSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStorage)(nil).GetSession), ctx, req)
}

// ListParticipants mocks base method.
func (m *MockStorage) ListParticipants(ctx context.Context, req persistence.ListParticipantsArg) (persistence.ListParticipantsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", ctx, req)
	ret0, _ := ret[0].(persistence.ListParticipantsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockStorageMockRecorder) ListParticipants(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockStorage)(nil).ListParticipants), ctx, req)
}

// ListSessions mocks base method.
func (m *MockStorage) ListSessions(ctx context.Context, req persistence.ListSessionsAg) (persistence.ListSessionsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, req)
	ret0, _ := ret[0].(persistence.ListSessionsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockStorageMockRecorder) ListSessions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockStorage)(nil).ListSessions), ctx, req)
}

// UpdateSession mocks base method.
func (m *MockStorage) UpdateSession(ctx context.Context, req persistence.UpdateSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockStorageMockRecorder) UpdateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockStorage)(nil).UpdateSession), ctx, req)
}

// WithTx mocks base method.
func (m *MockStorage) WithTx(ctx context.Context, fn func(context.Context, persistence.Storage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockStorageMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockStorage)(nil).WithTx), ctx, fn)
}

// MockLottery is a mock of Lottery interface.
type MockLottery struct {
	ctrl     *gomock.Controller
	recorder *MockLotteryMockRecorder
	isgomock struct{}
}

// MockLotteryMockRecorder is the mock recorder for MockLottery.
type MockLotteryMockRecorder struct {
	mock *MockLottery
}

// NewMockLottery creates a new mock instance.
func NewMockLottery(ctrl *gomock.Controller) *MockLottery {
	mock := &MockLottery{ctrl: ctrl}
	mock.recorder = &MockLotteryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLottery) EXPECT() *MockLotteryMockRecorder {
	return m.recorder
}

// Draw mocks base method.
func (m *MockLottery) Draw(ctx context.Context, arg lottery.DrawArg) (lottery.DrawRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Draw", ctx, arg)
	ret0, _ := ret[0].(lottery.DrawRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Draw indicates an expected call of Draw.
func (mr *MockLotteryMockRecorder) Draw(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockLottery)(nil).Draw), ctx, arg)
}

// GetProbabilities mocks base method.
func (m *MockLottery) GetProbabilities(ctx context.Context, arg lottery.GetProbabilitiesArg) (lottery.GetProbabilitiesRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProbabilities", ctx, arg)
	ret0, _ := ret[0].(lottery.GetProbabilitiesRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProbabilities indicates an expected call of GetProbabilities.
func (mr *MockLotteryMockRecorder) GetProbabilities(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProbabilities", reflect.TypeOf((*MockLottery)(nil).GetProbabilities), ctx, arg)
}

// StoreDrawResult mocks base method.
func (m *MockLottery) StoreDrawResult(ctx context.Context, arg lottery.StoreDrawResultArg) (lottery.StoreDrawResultRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreDrawResult", ctx, arg)
	ret0, _ := ret[0].(lottery.StoreDrawResultRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreDrawResult indicates an expected call of StoreDrawResult.
func (mr *MockLotteryMockRecorder) StoreDrawResult(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreDrawResult", reflect.TypeOf((*MockLottery)(nil).StoreDrawResult), ctx, arg)
}
