// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/moviehat (interfaces: Extractor)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/extractor.go . Extractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gatewayv1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
	isgomock struct{}
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockExtractor) Extract(ctx context.Context, session *gatewayv1.Session) (*gatewayv1.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, session)
	ret0, _ := ret[0].(*gatewayv1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockExtractorMockRecorder) Extract(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockExtractor)(nil).Extract), ctx, session)
}

// StoreExtraction mocks base method.
func (m *MockExtractor) StoreExtraction(ctx context.Context, session *gatewayv1.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreExtraction", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreExtraction indicates an expected call of StoreExtraction.
func (mr *MockExtractorMockRecorder) StoreExtraction(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreExtraction", reflect.TypeOf((*MockExtractor)(nil).StoreExtraction), ctx, session)
}
