// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/moviehat/persistence (interfaces: TransactionalStorage)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/store.go . TransactionalStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	persistence "github.com/stiflerGit/moviehat/internal/moviehat/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionalStorage is a mock of TransactionalStorage interface.
type MockTransactionalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionalStorageMockRecorder
	isgomock struct{}
}

// MockTransactionalStorageMockRecorder is the mock recorder for MockTransactionalStorage.
type MockTransactionalStorageMockRecorder struct {
	mock *MockTransactionalStorage
}

// NewMockTransactionalStorage creates a new mock instance.
func NewMockTransactionalStorage(ctrl *gomock.Controller) *MockTransactionalStorage {
	mock := &MockTransactionalStorage{ctrl: ctrl}
	mock.recorder = &MockTransactionalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionalStorage) EXPECT() *MockTransactionalStorageMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockTransactionalStorage) CloseSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockTransactionalStorageMockRecorder) CloseSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockTransactionalStorage)(nil).CloseSession), ctx, id)
}

// CreateMovie mocks base method.
func (m *MockTransactionalStorage) CreateMovie(ctx context.Context, req persistence.CreateMovieArg) (persistence.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovie", ctx, req)
	ret0, _ := ret[0].(persistence.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMovie indicates an expected call of CreateMovie.
func (mr *MockTransactionalStorageMockRecorder) CreateMovie(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovie", reflect.TypeOf((*MockTransactionalStorage)(nil).CreateMovie), ctx, req)
}

// CreateParticipant mocks base method.
func (m *MockTransactionalStorage) CreateParticipant(ctx context.Context, req persistence.CreateParticipantArg) (persistence.Participant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateParticipant", ctx, req)
	ret0, _ := ret[0].(persistence.Participant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateParticipant indicates an expected call of CreateParticipant.
func (mr *MockTransactionalStorageMockRecorder) CreateParticipant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateParticipant", reflect.TypeOf((*MockTransactionalStorage)(nil).CreateParticipant), ctx, req)
}

// CreateSession mocks base method.
func (m *MockTransactionalStorage) CreateSession(ctx context.Context, req persistence.CreateSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockTransactionalStorageMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockTransactionalStorage)(nil).CreateSession), ctx, req)
}

// CreateUser mocks base method.
func (m *MockTransactionalStorage) CreateUser(ctx context.Context, req persistence.CreateUserArg) (persistence.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(persistence.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockTransactionalStorageMockRecorder) CreateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockTransactionalStorage)(nil).CreateUser), ctx, req)
}

// DeleteMovie mocks base method.
func (m *MockTransactionalStorage) DeleteMovie(ctx context.Context, req persistence.DeleteMovieArg) (persistence.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMovie", ctx, req)
	ret0, _ := ret[0].(persistence.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMovie indicates an expected call of DeleteMovie.
func (mr *MockTransactionalStorageMockRecorder) DeleteMovie(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMovie", reflect.TypeOf((*MockTransactionalStorage)(nil).DeleteMovie), ctx, req)
}

// DeleteParticipant mocks base method.
func (m *MockTransactionalStorage) DeleteParticipant(ctx context.Context, req persistence.DeleteParticipantArg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteParticipant", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteParticipant indicates an expected call of DeleteParticipant.
func (mr *MockTransactionalStorageMockRecorder) DeleteParticipant(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteParticipant", reflect.TypeOf((*MockTransactionalStorage)(nil).DeleteParticipant), ctx, req)
}

// DeleteSession mocks base method.
func (m *MockTransactionalStorage) DeleteSession(ctx context.Context, id string) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockTransactionalStorageMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockTransactionalStorage)(nil).DeleteSession), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockTransactionalStorage) DeleteUser(ctx context.Context, req persistence.DeleteUserArg) (persistence.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, req)
	ret0, _ := ret[0].(persistence.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockTransactionalStorageMockRecorder) DeleteUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockTransactionalStorage)(nil).DeleteUser), ctx, req)
}

// GetMovie mocks base method.
func (m *MockTransactionalStorage) GetMovie(ctx context.Context, req persistence.GetMovieArg) (persistence.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", ctx, req)
	ret0, _ := ret[0].(persistence.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockTransactionalStorageMockRecorder) GetMovie(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockTransactionalStorage)(nil).GetMovie), ctx, req)
}

// GetSession mocks base method.
func (m *MockTransactionalStorage) GetSession(ctx context.Context, req persistence.GetSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockTransactionalStorageMockRecorder) GetSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockTransactionalStorage)(nil).GetSession), ctx, req)
}

// GetUser mocks base method.
func (m *MockTransactionalStorage) GetUser(ctx context.Context, req persistence.GetUserArg) (persistence.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, req)
	ret0, _ := ret[0].(persistence.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTransactionalStorageMockRecorder) GetUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTransactionalStorage)(nil).GetUser), ctx, req)
}

// ListMovies mocks base method.
func (m *MockTransactionalStorage) ListMovies(ctx context.Context, req persistence.ListMoviesArg) (persistence.ListMoviesRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMovies", ctx, req)
	ret0, _ := ret[0].(persistence.ListMoviesRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMovies indicates an expected call of ListMovies.
func (mr *MockTransactionalStorageMockRecorder) ListMovies(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMovies", reflect.TypeOf((*MockTransactionalStorage)(nil).ListMovies), ctx, req)
}

// ListParticipants mocks base method.
func (m *MockTransactionalStorage) ListParticipants(ctx context.Context, req persistence.ListParticipantsArg) (persistence.ListParticipantsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParticipants", ctx, req)
	ret0, _ := ret[0].(persistence.ListParticipantsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParticipants indicates an expected call of ListParticipants.
func (mr *MockTransactionalStorageMockRecorder) ListParticipants(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParticipants", reflect.TypeOf((*MockTransactionalStorage)(nil).ListParticipants), ctx, req)
}

// ListSessions mocks base method.
func (m *MockTransactionalStorage) ListSessions(ctx context.Context, req persistence.ListSessionsAg) (persistence.ListSessionsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions", ctx, req)
	ret0, _ := ret[0].(persistence.ListSessionsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockTransactionalStorageMockRecorder) ListSessions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockTransactionalStorage)(nil).ListSessions), ctx, req)
}

// ListUsers mocks base method.
func (m *MockTransactionalStorage) ListUsers(ctx context.Context, req persistence.ListUsersArg) ([]persistence.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, req)
	ret0, _ := ret[0].([]persistence.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockTransactionalStorageMockRecorder) ListUsers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockTransactionalStorage)(nil).ListUsers), ctx, req)
}

// UpdateMovie mocks base method.
func (m *MockTransactionalStorage) UpdateMovie(ctx context.Context, req persistence.UpdateMovieArg) (persistence.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMovie", ctx, req)
	ret0, _ := ret[0].(persistence.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMovie indicates an expected call of UpdateMovie.
func (mr *MockTransactionalStorageMockRecorder) UpdateMovie(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMovie", reflect.TypeOf((*MockTransactionalStorage)(nil).UpdateMovie), ctx, req)
}

// UpdateSession mocks base method.
func (m *MockTransactionalStorage) UpdateSession(ctx context.Context, req persistence.UpdateSessionArg) (persistence.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, req)
	ret0, _ := ret[0].(persistence.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockTransactionalStorageMockRecorder) UpdateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockTransactionalStorage)(nil).UpdateSession), ctx, req)
}

// UpdateUser mocks base method.
func (m *MockTransactionalStorage) UpdateUser(ctx context.Context, req persistence.UpdateUserArg) (persistence.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, req)
	ret0, _ := ret[0].(persistence.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockTransactionalStorageMockRecorder) UpdateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockTransactionalStorage)(nil).UpdateUser), ctx, req)
}

// WithTx mocks base method.
func (m *MockTransactionalStorage) WithTx(ctx context.Context, fn func(context.Context, persistence.Storage) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactionalStorageMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactionalStorage)(nil).WithTx), ctx, fn)
}
