// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/moviesearch (interfaces: MoviesSearcher)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/movie_searcher.go . MoviesSearcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	moviesearch "github.com/stiflerGit/moviehat/internal/moviesearch"
	gomock "go.uber.org/mock/gomock"
)

// MockMoviesSearcher is a mock of MoviesSearcher interface.
type MockMoviesSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockMoviesSearcherMockRecorder
	isgomock struct{}
}

// MockMoviesSearcherMockRecorder is the mock recorder for MockMoviesSearcher.
type MockMoviesSearcherMockRecorder struct {
	mock *MockMoviesSearcher
}

// NewMockMoviesSearcher creates a new mock instance.
func NewMockMoviesSearcher(ctrl *gomock.Controller) *MockMoviesSearcher {
	mock := &MockMoviesSearcher{ctrl: ctrl}
	mock.recorder = &MockMoviesSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMoviesSearcher) EXPECT() *MockMoviesSearcherMockRecorder {
	return m.recorder
}

// SearchMovies mocks base method.
func (m *MockMoviesSearcher) SearchMovies(ctx context.Context, arg moviesearch.SearchMoviesArg) (moviesearch.SearchMoviesRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMovies", ctx, arg)
	ret0, _ := ret[0].(moviesearch.SearchMoviesRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMovies indicates an expected call of SearchMovies.
func (mr *MockMoviesSearcherMockRecorder) SearchMovies(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMovies", reflect.TypeOf((*MockMoviesSearcher)(nil).SearchMovies), ctx, arg)
}
