// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/moviesearch (interfaces: MovieDetailsGetter)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/movie_details_getter.go . MovieDetailsGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	moviesearch "github.com/stiflerGit/moviehat/internal/moviesearch"
	gomock "go.uber.org/mock/gomock"
)

// MockMovieDetailsGetter is a mock of MovieDetailsGetter interface.
type MockMovieDetailsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMovieDetailsGetterMockRecorder
	isgomock struct{}
}

// MockMovieDetailsGetterMockRecorder is the mock recorder for MockMovieDetailsGetter.
type MockMovieDetailsGetterMockRecorder struct {
	mock *MockMovieDetailsGetter
}

// NewMockMovieDetailsGetter creates a new mock instance.
func NewMockMovieDetailsGetter(ctrl *gomock.Controller) *MockMovieDetailsGetter {
	mock := &MockMovieDetailsGetter{ctrl: ctrl}
	mock.recorder = &MockMovieDetailsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieDetailsGetter) EXPECT() *MockMovieDetailsGetterMockRecorder {
	return m.recorder
}

// GetDetails mocks base method.
func (m *MockMovieDetailsGetter) GetDetails(ctx context.Context, arg moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, arg)
	ret0, _ := ret[0].(moviesearch.GetDetailsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockMovieDetailsGetterMockRecorder) GetDetails(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockMovieDetailsGetter)(nil).GetDetails), ctx, arg)
}
