// Code generated by MockGen. DO NOT EDIT.
// Source: internal/moviesearch/types.go
//
// Generated by this command:
//
//	mockgen -source internal/moviesearch/types.go -destination internal/moviesearch/mocks/provider.go -package mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	moviesearch "github.com/stiflerGit/moviehat/internal/moviesearch"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetDetails mocks base method.
func (m *MockProvider) GetDetails(ctx context.Context, arg moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, arg)
	ret0, _ := ret[0].(moviesearch.GetDetailsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockProviderMockRecorder) GetDetails(ctx, arg any) *MockProviderGetDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockProvider)(nil).GetDetails), ctx, arg)
	return &MockProviderGetDetailsCall{Call: call}
}

// MockProviderGetDetailsCall wrap *gomock.Call
type MockProviderGetDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderGetDetailsCall) Return(arg0 moviesearch.GetDetailsRet, arg1 error) *MockProviderGetDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderGetDetailsCall) Do(f func(context.Context, moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error)) *MockProviderGetDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderGetDetailsCall) DoAndReturn(f func(context.Context, moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error)) *MockProviderGetDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Search mocks base method.
func (m *MockProvider) Search(ctx context.Context, arg moviesearch.SearchArg) (moviesearch.SearchRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, arg)
	ret0, _ := ret[0].(moviesearch.SearchRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockProviderMockRecorder) Search(ctx, arg any) *MockProviderSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockProvider)(nil).Search), ctx, arg)
	return &MockProviderSearchCall{Call: call}
}

// MockProviderSearchCall wrap *gomock.Call
type MockProviderSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderSearchCall) Return(arg0 moviesearch.SearchRet, arg1 error) *MockProviderSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderSearchCall) Do(f func(context.Context, moviesearch.SearchArg) (moviesearch.SearchRet, error)) *MockProviderSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderSearchCall) DoAndReturn(f func(context.Context, moviesearch.SearchArg) (moviesearch.SearchRet, error)) *MockProviderSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMovieSearcher is a mock of MovieSearcher interface.
type MockMovieSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockMovieSearcherMockRecorder
	isgomock struct{}
}

// MockMovieSearcherMockRecorder is the mock recorder for MockMovieSearcher.
type MockMovieSearcherMockRecorder struct {
	mock *MockMovieSearcher
}

// NewMockMovieSearcher creates a new mock instance.
func NewMockMovieSearcher(ctrl *gomock.Controller) *MockMovieSearcher {
	mock := &MockMovieSearcher{ctrl: ctrl}
	mock.recorder = &MockMovieSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieSearcher) EXPECT() *MockMovieSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockMovieSearcher) Search(ctx context.Context, arg moviesearch.SearchArg) (moviesearch.SearchRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, arg)
	ret0, _ := ret[0].(moviesearch.SearchRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockMovieSearcherMockRecorder) Search(ctx, arg any) *MockMovieSearcherSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockMovieSearcher)(nil).Search), ctx, arg)
	return &MockMovieSearcherSearchCall{Call: call}
}

// MockMovieSearcherSearchCall wrap *gomock.Call
type MockMovieSearcherSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMovieSearcherSearchCall) Return(arg0 moviesearch.SearchRet, arg1 error) *MockMovieSearcherSearchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMovieSearcherSearchCall) Do(f func(context.Context, moviesearch.SearchArg) (moviesearch.SearchRet, error)) *MockMovieSearcherSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMovieSearcherSearchCall) DoAndReturn(f func(context.Context, moviesearch.SearchArg) (moviesearch.SearchRet, error)) *MockMovieSearcherSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMovieDetailsGetter is a mock of MovieDetailsGetter interface.
type MockMovieDetailsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMovieDetailsGetterMockRecorder
	isgomock struct{}
}

// MockMovieDetailsGetterMockRecorder is the mock recorder for MockMovieDetailsGetter.
type MockMovieDetailsGetterMockRecorder struct {
	mock *MockMovieDetailsGetter
}

// NewMockMovieDetailsGetter creates a new mock instance.
func NewMockMovieDetailsGetter(ctrl *gomock.Controller) *MockMovieDetailsGetter {
	mock := &MockMovieDetailsGetter{ctrl: ctrl}
	mock.recorder = &MockMovieDetailsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMovieDetailsGetter) EXPECT() *MockMovieDetailsGetterMockRecorder {
	return m.recorder
}

// GetDetails mocks base method.
func (m *MockMovieDetailsGetter) GetDetails(ctx context.Context, arg moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetails", ctx, arg)
	ret0, _ := ret[0].(moviesearch.GetDetailsRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetails indicates an expected call of GetDetails.
func (mr *MockMovieDetailsGetterMockRecorder) GetDetails(ctx, arg any) *MockMovieDetailsGetterGetDetailsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetails", reflect.TypeOf((*MockMovieDetailsGetter)(nil).GetDetails), ctx, arg)
	return &MockMovieDetailsGetterGetDetailsCall{Call: call}
}

// MockMovieDetailsGetterGetDetailsCall wrap *gomock.Call
type MockMovieDetailsGetterGetDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMovieDetailsGetterGetDetailsCall) Return(arg0 moviesearch.GetDetailsRet, arg1 error) *MockMovieDetailsGetterGetDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMovieDetailsGetterGetDetailsCall) Do(f func(context.Context, moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error)) *MockMovieDetailsGetterGetDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMovieDetailsGetterGetDetailsCall) DoAndReturn(f func(context.Context, moviesearch.GetDetailsArg) (moviesearch.GetDetailsRet, error)) *MockMovieDetailsGetterGetDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
