// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: gateway/v1/gateway.proto

package gatewayv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/stiflerGit/moviehat/api/gateway/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GatewayServiceName is the fully-qualified name of the GatewayService service.
	GatewayServiceName = "gateway.v1.GatewayService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GatewayServiceCreateInvitationProcedure is the fully-qualified name of the GatewayService's
	// CreateInvitation RPC.
	GatewayServiceCreateInvitationProcedure = "/gateway.v1.GatewayService/CreateInvitation"
	// GatewayServiceSignUpProcedure is the fully-qualified name of the GatewayService's SignUp RPC.
	GatewayServiceSignUpProcedure = "/gateway.v1.GatewayService/SignUp"
	// GatewayServiceSignInProcedure is the fully-qualified name of the GatewayService's SignIn RPC.
	GatewayServiceSignInProcedure = "/gateway.v1.GatewayService/SignIn"
	// GatewayServiceSignOutProcedure is the fully-qualified name of the GatewayService's SignOut RPC.
	GatewayServiceSignOutProcedure = "/gateway.v1.GatewayService/SignOut"
	// GatewayServiceListUsersProcedure is the fully-qualified name of the GatewayService's ListUsers
	// RPC.
	GatewayServiceListUsersProcedure = "/gateway.v1.GatewayService/ListUsers"
	// GatewayServiceUpdateUserProcedure is the fully-qualified name of the GatewayService's UpdateUser
	// RPC.
	GatewayServiceUpdateUserProcedure = "/gateway.v1.GatewayService/UpdateUser"
	// GatewayServiceDeleteUserProcedure is the fully-qualified name of the GatewayService's DeleteUser
	// RPC.
	GatewayServiceDeleteUserProcedure = "/gateway.v1.GatewayService/DeleteUser"
	// GatewayServiceCreateSessionProcedure is the fully-qualified name of the GatewayService's
	// CreateSession RPC.
	GatewayServiceCreateSessionProcedure = "/gateway.v1.GatewayService/CreateSession"
	// GatewayServiceListSessionsProcedure is the fully-qualified name of the GatewayService's
	// ListSessions RPC.
	GatewayServiceListSessionsProcedure = "/gateway.v1.GatewayService/ListSessions"
	// GatewayServiceGetSessionProcedure is the fully-qualified name of the GatewayService's GetSession
	// RPC.
	GatewayServiceGetSessionProcedure = "/gateway.v1.GatewayService/GetSession"
	// GatewayServiceEndSessionProcedure is the fully-qualified name of the GatewayService's EndSession
	// RPC.
	GatewayServiceEndSessionProcedure = "/gateway.v1.GatewayService/EndSession"
	// GatewayServiceSetSessionMovieProcedure is the fully-qualified name of the GatewayService's
	// SetSessionMovie RPC.
	GatewayServiceSetSessionMovieProcedure = "/gateway.v1.GatewayService/SetSessionMovie"
	// GatewayServiceDeleteSessionProcedure is the fully-qualified name of the GatewayService's
	// DeleteSession RPC.
	GatewayServiceDeleteSessionProcedure = "/gateway.v1.GatewayService/DeleteSession"
	// GatewayServiceAddParticipantProcedure is the fully-qualified name of the GatewayService's
	// AddParticipant RPC.
	GatewayServiceAddParticipantProcedure = "/gateway.v1.GatewayService/AddParticipant"
	// GatewayServiceRemoveParticipantProcedure is the fully-qualified name of the GatewayService's
	// RemoveParticipant RPC.
	GatewayServiceRemoveParticipantProcedure = "/gateway.v1.GatewayService/RemoveParticipant"
	// GatewayServiceListParticipantsProcedure is the fully-qualified name of the GatewayService's
	// ListParticipants RPC.
	GatewayServiceListParticipantsProcedure = "/gateway.v1.GatewayService/ListParticipants"
	// GatewayServiceAddUserMovieProcedure is the fully-qualified name of the GatewayService's
	// AddUserMovie RPC.
	GatewayServiceAddUserMovieProcedure = "/gateway.v1.GatewayService/AddUserMovie"
	// GatewayServiceListUserMoviesProcedure is the fully-qualified name of the GatewayService's
	// ListUserMovies RPC.
	GatewayServiceListUserMoviesProcedure = "/gateway.v1.GatewayService/ListUserMovies"
	// GatewayServiceDeleteUserMovieProcedure is the fully-qualified name of the GatewayService's
	// DeleteUserMovie RPC.
	GatewayServiceDeleteUserMovieProcedure = "/gateway.v1.GatewayService/DeleteUserMovie"
)

// GatewayServiceClient is a client for the gateway.v1.GatewayService service.
type GatewayServiceClient interface {
	CreateInvitation(context.Context, *v1.CreateInvitationRequest) (*v1.CreateInvitationResponse, error)
	SignUp(context.Context, *v1.SignUpRequest) (*v1.SignUpResponse, error)
	SignIn(context.Context, *v1.SignInRequest) (*v1.SignInResponse, error)
	SignOut(context.Context, *v1.SignOutRequest) (*v1.SignOutResponse, error)
	ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error)
	UpdateUser(context.Context, *v1.UpdateUserRequest) (*v1.UpdateUserResponse, error)
	DeleteUser(context.Context, *v1.DeleteUserRequest) (*v1.DeleteUserResponse, error)
	CreateSession(context.Context, *v1.CreateSessionRequest) (*v1.CreateSessionResponse, error)
	ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error)
	GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error)
	EndSession(context.Context, *v1.EndSessionRequest) (*v1.EndSessionResponse, error)
	SetSessionMovie(context.Context, *v1.SetSessionMovieRequest) (*v1.SetSessionMovieResponse, error)
	DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error)
	AddParticipant(context.Context, *v1.AddParticipantRequest) (*v1.AddParticipantResponse, error)
	RemoveParticipant(context.Context, *v1.RemoveParticipantRequest) (*v1.RemoveParticipantResponse, error)
	ListParticipants(context.Context, *v1.ListParticipantsRequest) (*v1.ListParticipantsResponse, error)
	AddUserMovie(context.Context, *v1.AddUserMovieRequest) (*v1.AddUserMovieResponse, error)
	ListUserMovies(context.Context, *v1.ListUserMoviesRequest) (*v1.ListUserMoviesResponse, error)
	DeleteUserMovie(context.Context, *v1.DeleteUserMovieRequest) (*v1.DeleteUserMovieResponse, error)
}

// NewGatewayServiceClient constructs a client for the gateway.v1.GatewayService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGatewayServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GatewayServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gatewayServiceMethods := v1.File_gateway_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	return &gatewayServiceClient{
		createInvitation: connect.NewClient[v1.CreateInvitationRequest, v1.CreateInvitationResponse](
			httpClient,
			baseURL+GatewayServiceCreateInvitationProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CreateInvitation")),
			connect.WithClientOptions(opts...),
		),
		signUp: connect.NewClient[v1.SignUpRequest, v1.SignUpResponse](
			httpClient,
			baseURL+GatewayServiceSignUpProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("SignUp")),
			connect.WithClientOptions(opts...),
		),
		signIn: connect.NewClient[v1.SignInRequest, v1.SignInResponse](
			httpClient,
			baseURL+GatewayServiceSignInProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("SignIn")),
			connect.WithClientOptions(opts...),
		),
		signOut: connect.NewClient[v1.SignOutRequest, v1.SignOutResponse](
			httpClient,
			baseURL+GatewayServiceSignOutProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("SignOut")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+GatewayServiceListUsersProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+GatewayServiceUpdateUserProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserRequest, v1.DeleteUserResponse](
			httpClient,
			baseURL+GatewayServiceDeleteUserProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+GatewayServiceCreateSessionProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+GatewayServiceListSessionsProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+GatewayServiceGetSessionProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[v1.EndSessionRequest, v1.EndSessionResponse](
			httpClient,
			baseURL+GatewayServiceEndSessionProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		setSessionMovie: connect.NewClient[v1.SetSessionMovieRequest, v1.SetSessionMovieResponse](
			httpClient,
			baseURL+GatewayServiceSetSessionMovieProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("SetSessionMovie")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v1.DeleteSessionRequest, v1.DeleteSessionResponse](
			httpClient,
			baseURL+GatewayServiceDeleteSessionProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
		addParticipant: connect.NewClient[v1.AddParticipantRequest, v1.AddParticipantResponse](
			httpClient,
			baseURL+GatewayServiceAddParticipantProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("AddParticipant")),
			connect.WithClientOptions(opts...),
		),
		removeParticipant: connect.NewClient[v1.RemoveParticipantRequest, v1.RemoveParticipantResponse](
			httpClient,
			baseURL+GatewayServiceRemoveParticipantProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("RemoveParticipant")),
			connect.WithClientOptions(opts...),
		),
		listParticipants: connect.NewClient[v1.ListParticipantsRequest, v1.ListParticipantsResponse](
			httpClient,
			baseURL+GatewayServiceListParticipantsProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListParticipants")),
			connect.WithClientOptions(opts...),
		),
		addUserMovie: connect.NewClient[v1.AddUserMovieRequest, v1.AddUserMovieResponse](
			httpClient,
			baseURL+GatewayServiceAddUserMovieProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("AddUserMovie")),
			connect.WithClientOptions(opts...),
		),
		listUserMovies: connect.NewClient[v1.ListUserMoviesRequest, v1.ListUserMoviesResponse](
			httpClient,
			baseURL+GatewayServiceListUserMoviesProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("ListUserMovies")),
			connect.WithClientOptions(opts...),
		),
		deleteUserMovie: connect.NewClient[v1.DeleteUserMovieRequest, v1.DeleteUserMovieResponse](
			httpClient,
			baseURL+GatewayServiceDeleteUserMovieProcedure,
			connect.WithSchema(gatewayServiceMethods.ByName("DeleteUserMovie")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gatewayServiceClient implements GatewayServiceClient.
type gatewayServiceClient struct {
	createInvitation  *connect.Client[v1.CreateInvitationRequest, v1.CreateInvitationResponse]
	signUp            *connect.Client[v1.SignUpRequest, v1.SignUpResponse]
	signIn            *connect.Client[v1.SignInRequest, v1.SignInResponse]
	signOut           *connect.Client[v1.SignOutRequest, v1.SignOutResponse]
	listUsers         *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	updateUser        *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	deleteUser        *connect.Client[v1.DeleteUserRequest, v1.DeleteUserResponse]
	createSession     *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	listSessions      *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession        *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	endSession        *connect.Client[v1.EndSessionRequest, v1.EndSessionResponse]
	setSessionMovie   *connect.Client[v1.SetSessionMovieRequest, v1.SetSessionMovieResponse]
	deleteSession     *connect.Client[v1.DeleteSessionRequest, v1.DeleteSessionResponse]
	addParticipant    *connect.Client[v1.AddParticipantRequest, v1.AddParticipantResponse]
	removeParticipant *connect.Client[v1.RemoveParticipantRequest, v1.RemoveParticipantResponse]
	listParticipants  *connect.Client[v1.ListParticipantsRequest, v1.ListParticipantsResponse]
	addUserMovie      *connect.Client[v1.AddUserMovieRequest, v1.AddUserMovieResponse]
	listUserMovies    *connect.Client[v1.ListUserMoviesRequest, v1.ListUserMoviesResponse]
	deleteUserMovie   *connect.Client[v1.DeleteUserMovieRequest, v1.DeleteUserMovieResponse]
}

// CreateInvitation calls gateway.v1.GatewayService.CreateInvitation.
func (c *gatewayServiceClient) CreateInvitation(ctx context.Context, req *v1.CreateInvitationRequest) (*v1.CreateInvitationResponse, error) {
	response, err := c.createInvitation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SignUp calls gateway.v1.GatewayService.SignUp.
func (c *gatewayServiceClient) SignUp(ctx context.Context, req *v1.SignUpRequest) (*v1.SignUpResponse, error) {
	response, err := c.signUp.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SignIn calls gateway.v1.GatewayService.SignIn.
func (c *gatewayServiceClient) SignIn(ctx context.Context, req *v1.SignInRequest) (*v1.SignInResponse, error) {
	response, err := c.signIn.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SignOut calls gateway.v1.GatewayService.SignOut.
func (c *gatewayServiceClient) SignOut(ctx context.Context, req *v1.SignOutRequest) (*v1.SignOutResponse, error) {
	response, err := c.signOut.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListUsers calls gateway.v1.GatewayService.ListUsers.
func (c *gatewayServiceClient) ListUsers(ctx context.Context, req *v1.ListUsersRequest) (*v1.ListUsersResponse, error) {
	response, err := c.listUsers.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateUser calls gateway.v1.GatewayService.UpdateUser.
func (c *gatewayServiceClient) UpdateUser(ctx context.Context, req *v1.UpdateUserRequest) (*v1.UpdateUserResponse, error) {
	response, err := c.updateUser.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteUser calls gateway.v1.GatewayService.DeleteUser.
func (c *gatewayServiceClient) DeleteUser(ctx context.Context, req *v1.DeleteUserRequest) (*v1.DeleteUserResponse, error) {
	response, err := c.deleteUser.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateSession calls gateway.v1.GatewayService.CreateSession.
func (c *gatewayServiceClient) CreateSession(ctx context.Context, req *v1.CreateSessionRequest) (*v1.CreateSessionResponse, error) {
	response, err := c.createSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSessions calls gateway.v1.GatewayService.ListSessions.
func (c *gatewayServiceClient) ListSessions(ctx context.Context, req *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error) {
	response, err := c.listSessions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSession calls gateway.v1.GatewayService.GetSession.
func (c *gatewayServiceClient) GetSession(ctx context.Context, req *v1.GetSessionRequest) (*v1.GetSessionResponse, error) {
	response, err := c.getSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EndSession calls gateway.v1.GatewayService.EndSession.
func (c *gatewayServiceClient) EndSession(ctx context.Context, req *v1.EndSessionRequest) (*v1.EndSessionResponse, error) {
	response, err := c.endSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetSessionMovie calls gateway.v1.GatewayService.SetSessionMovie.
func (c *gatewayServiceClient) SetSessionMovie(ctx context.Context, req *v1.SetSessionMovieRequest) (*v1.SetSessionMovieResponse, error) {
	response, err := c.setSessionMovie.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteSession calls gateway.v1.GatewayService.DeleteSession.
func (c *gatewayServiceClient) DeleteSession(ctx context.Context, req *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error) {
	response, err := c.deleteSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddParticipant calls gateway.v1.GatewayService.AddParticipant.
func (c *gatewayServiceClient) AddParticipant(ctx context.Context, req *v1.AddParticipantRequest) (*v1.AddParticipantResponse, error) {
	response, err := c.addParticipant.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveParticipant calls gateway.v1.GatewayService.RemoveParticipant.
func (c *gatewayServiceClient) RemoveParticipant(ctx context.Context, req *v1.RemoveParticipantRequest) (*v1.RemoveParticipantResponse, error) {
	response, err := c.removeParticipant.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListParticipants calls gateway.v1.GatewayService.ListParticipants.
func (c *gatewayServiceClient) ListParticipants(ctx context.Context, req *v1.ListParticipantsRequest) (*v1.ListParticipantsResponse, error) {
	response, err := c.listParticipants.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AddUserMovie calls gateway.v1.GatewayService.AddUserMovie.
func (c *gatewayServiceClient) AddUserMovie(ctx context.Context, req *v1.AddUserMovieRequest) (*v1.AddUserMovieResponse, error) {
	response, err := c.addUserMovie.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListUserMovies calls gateway.v1.GatewayService.ListUserMovies.
func (c *gatewayServiceClient) ListUserMovies(ctx context.Context, req *v1.ListUserMoviesRequest) (*v1.ListUserMoviesResponse, error) {
	response, err := c.listUserMovies.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteUserMovie calls gateway.v1.GatewayService.DeleteUserMovie.
func (c *gatewayServiceClient) DeleteUserMovie(ctx context.Context, req *v1.DeleteUserMovieRequest) (*v1.DeleteUserMovieResponse, error) {
	response, err := c.deleteUserMovie.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GatewayServiceHandler is an implementation of the gateway.v1.GatewayService service.
type GatewayServiceHandler interface {
	CreateInvitation(context.Context, *v1.CreateInvitationRequest) (*v1.CreateInvitationResponse, error)
	SignUp(context.Context, *v1.SignUpRequest) (*v1.SignUpResponse, error)
	SignIn(context.Context, *v1.SignInRequest) (*v1.SignInResponse, error)
	SignOut(context.Context, *v1.SignOutRequest) (*v1.SignOutResponse, error)
	ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error)
	UpdateUser(context.Context, *v1.UpdateUserRequest) (*v1.UpdateUserResponse, error)
	DeleteUser(context.Context, *v1.DeleteUserRequest) (*v1.DeleteUserResponse, error)
	CreateSession(context.Context, *v1.CreateSessionRequest) (*v1.CreateSessionResponse, error)
	ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error)
	GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error)
	EndSession(context.Context, *v1.EndSessionRequest) (*v1.EndSessionResponse, error)
	SetSessionMovie(context.Context, *v1.SetSessionMovieRequest) (*v1.SetSessionMovieResponse, error)
	DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error)
	AddParticipant(context.Context, *v1.AddParticipantRequest) (*v1.AddParticipantResponse, error)
	RemoveParticipant(context.Context, *v1.RemoveParticipantRequest) (*v1.RemoveParticipantResponse, error)
	ListParticipants(context.Context, *v1.ListParticipantsRequest) (*v1.ListParticipantsResponse, error)
	AddUserMovie(context.Context, *v1.AddUserMovieRequest) (*v1.AddUserMovieResponse, error)
	ListUserMovies(context.Context, *v1.ListUserMoviesRequest) (*v1.ListUserMoviesResponse, error)
	DeleteUserMovie(context.Context, *v1.DeleteUserMovieRequest) (*v1.DeleteUserMovieResponse, error)
}

// NewGatewayServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGatewayServiceHandler(svc GatewayServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gatewayServiceMethods := v1.File_gateway_v1_gateway_proto.Services().ByName("GatewayService").Methods()
	gatewayServiceCreateInvitationHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceCreateInvitationProcedure,
		svc.CreateInvitation,
		connect.WithSchema(gatewayServiceMethods.ByName("CreateInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceSignUpHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceSignUpProcedure,
		svc.SignUp,
		connect.WithSchema(gatewayServiceMethods.ByName("SignUp")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceSignInHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceSignInProcedure,
		svc.SignIn,
		connect.WithSchema(gatewayServiceMethods.ByName("SignIn")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceSignOutHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceSignOutProcedure,
		svc.SignOut,
		connect.WithSchema(gatewayServiceMethods.ByName("SignOut")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListUsersHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(gatewayServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceUpdateUserHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(gatewayServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteUserHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceCreateSessionHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(gatewayServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListSessionsHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(gatewayServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceGetSessionHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(gatewayServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceEndSessionHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(gatewayServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceSetSessionMovieHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceSetSessionMovieProcedure,
		svc.SetSessionMovie,
		connect.WithSchema(gatewayServiceMethods.ByName("SetSessionMovie")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteSessionHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceAddParticipantHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceAddParticipantProcedure,
		svc.AddParticipant,
		connect.WithSchema(gatewayServiceMethods.ByName("AddParticipant")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceRemoveParticipantHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceRemoveParticipantProcedure,
		svc.RemoveParticipant,
		connect.WithSchema(gatewayServiceMethods.ByName("RemoveParticipant")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListParticipantsHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceListParticipantsProcedure,
		svc.ListParticipants,
		connect.WithSchema(gatewayServiceMethods.ByName("ListParticipants")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceAddUserMovieHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceAddUserMovieProcedure,
		svc.AddUserMovie,
		connect.WithSchema(gatewayServiceMethods.ByName("AddUserMovie")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceListUserMoviesHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceListUserMoviesProcedure,
		svc.ListUserMovies,
		connect.WithSchema(gatewayServiceMethods.ByName("ListUserMovies")),
		connect.WithHandlerOptions(opts...),
	)
	gatewayServiceDeleteUserMovieHandler := connect.NewUnaryHandlerSimple(
		GatewayServiceDeleteUserMovieProcedure,
		svc.DeleteUserMovie,
		connect.WithSchema(gatewayServiceMethods.ByName("DeleteUserMovie")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gateway.v1.GatewayService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GatewayServiceCreateInvitationProcedure:
			gatewayServiceCreateInvitationHandler.ServeHTTP(w, r)
		case GatewayServiceSignUpProcedure:
			gatewayServiceSignUpHandler.ServeHTTP(w, r)
		case GatewayServiceSignInProcedure:
			gatewayServiceSignInHandler.ServeHTTP(w, r)
		case GatewayServiceSignOutProcedure:
			gatewayServiceSignOutHandler.ServeHTTP(w, r)
		case GatewayServiceListUsersProcedure:
			gatewayServiceListUsersHandler.ServeHTTP(w, r)
		case GatewayServiceUpdateUserProcedure:
			gatewayServiceUpdateUserHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteUserProcedure:
			gatewayServiceDeleteUserHandler.ServeHTTP(w, r)
		case GatewayServiceCreateSessionProcedure:
			gatewayServiceCreateSessionHandler.ServeHTTP(w, r)
		case GatewayServiceListSessionsProcedure:
			gatewayServiceListSessionsHandler.ServeHTTP(w, r)
		case GatewayServiceGetSessionProcedure:
			gatewayServiceGetSessionHandler.ServeHTTP(w, r)
		case GatewayServiceEndSessionProcedure:
			gatewayServiceEndSessionHandler.ServeHTTP(w, r)
		case GatewayServiceSetSessionMovieProcedure:
			gatewayServiceSetSessionMovieHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteSessionProcedure:
			gatewayServiceDeleteSessionHandler.ServeHTTP(w, r)
		case GatewayServiceAddParticipantProcedure:
			gatewayServiceAddParticipantHandler.ServeHTTP(w, r)
		case GatewayServiceRemoveParticipantProcedure:
			gatewayServiceRemoveParticipantHandler.ServeHTTP(w, r)
		case GatewayServiceListParticipantsProcedure:
			gatewayServiceListParticipantsHandler.ServeHTTP(w, r)
		case GatewayServiceAddUserMovieProcedure:
			gatewayServiceAddUserMovieHandler.ServeHTTP(w, r)
		case GatewayServiceListUserMoviesProcedure:
			gatewayServiceListUserMoviesHandler.ServeHTTP(w, r)
		case GatewayServiceDeleteUserMovieProcedure:
			gatewayServiceDeleteUserMovieHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGatewayServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGatewayServiceHandler struct{}

func (UnimplementedGatewayServiceHandler) CreateInvitation(context.Context, *v1.CreateInvitationRequest) (*v1.CreateInvitationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.CreateInvitation is not implemented"))
}

func (UnimplementedGatewayServiceHandler) SignUp(context.Context, *v1.SignUpRequest) (*v1.SignUpResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.SignUp is not implemented"))
}

func (UnimplementedGatewayServiceHandler) SignIn(context.Context, *v1.SignInRequest) (*v1.SignInResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.SignIn is not implemented"))
}

func (UnimplementedGatewayServiceHandler) SignOut(context.Context, *v1.SignOutRequest) (*v1.SignOutResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.SignOut is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListUsers(context.Context, *v1.ListUsersRequest) (*v1.ListUsersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.ListUsers is not implemented"))
}

func (UnimplementedGatewayServiceHandler) UpdateUser(context.Context, *v1.UpdateUserRequest) (*v1.UpdateUserResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.UpdateUser is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteUser(context.Context, *v1.DeleteUserRequest) (*v1.DeleteUserResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.DeleteUser is not implemented"))
}

func (UnimplementedGatewayServiceHandler) CreateSession(context.Context, *v1.CreateSessionRequest) (*v1.CreateSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.CreateSession is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.ListSessions is not implemented"))
}

func (UnimplementedGatewayServiceHandler) GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.GetSession is not implemented"))
}

func (UnimplementedGatewayServiceHandler) EndSession(context.Context, *v1.EndSessionRequest) (*v1.EndSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.EndSession is not implemented"))
}

func (UnimplementedGatewayServiceHandler) SetSessionMovie(context.Context, *v1.SetSessionMovieRequest) (*v1.SetSessionMovieResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.SetSessionMovie is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.DeleteSession is not implemented"))
}

func (UnimplementedGatewayServiceHandler) AddParticipant(context.Context, *v1.AddParticipantRequest) (*v1.AddParticipantResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.AddParticipant is not implemented"))
}

func (UnimplementedGatewayServiceHandler) RemoveParticipant(context.Context, *v1.RemoveParticipantRequest) (*v1.RemoveParticipantResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.RemoveParticipant is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListParticipants(context.Context, *v1.ListParticipantsRequest) (*v1.ListParticipantsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.ListParticipants is not implemented"))
}

func (UnimplementedGatewayServiceHandler) AddUserMovie(context.Context, *v1.AddUserMovieRequest) (*v1.AddUserMovieResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.AddUserMovie is not implemented"))
}

func (UnimplementedGatewayServiceHandler) ListUserMovies(context.Context, *v1.ListUserMoviesRequest) (*v1.ListUserMoviesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.ListUserMovies is not implemented"))
}

func (UnimplementedGatewayServiceHandler) DeleteUserMovie(context.Context, *v1.DeleteUserMovieRequest) (*v1.DeleteUserMovieResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gateway.v1.GatewayService.DeleteUserMovie is not implemented"))
}
