// Code generated by MockGen. DO NOT EDIT.
// Source: /home/stefano/workspace/github.com/stiflerGit/MovieHat/internal/moviesearch/provider/tmdb/provider.go
//
// Generated by this command:
//
//	mockgen -source /home/stefano/workspace/github.com/stiflerGit/MovieHat/internal/moviesearch/provider/tmdb/provider.go -destination /home/stefano/workspace/github.com/stiflerGit/MovieHat/internal/moviesearch/provider/tmdb/mocks/client.go -package mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	client "github.com/stiflerGit/moviehat/gen/tmdb"
	gomock "go.uber.org/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// MovieDetails mocks base method.
func (m *MockClientInterface) MovieDetails(ctx context.Context, movieId int32, params *client.MovieDetailsParams, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, movieId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MovieDetails", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MovieDetails indicates an expected call of MovieDetails.
func (mr *MockClientInterfaceMockRecorder) MovieDetails(ctx, movieId, params any, reqEditors ...any) *MockClientInterfaceMovieDetailsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, movieId, params}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MovieDetails", reflect.TypeOf((*MockClientInterface)(nil).MovieDetails), varargs...)
	return &MockClientInterfaceMovieDetailsCall{Call: call}
}

// MockClientInterfaceMovieDetailsCall wrap *gomock.Call
type MockClientInterfaceMovieDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientInterfaceMovieDetailsCall) Return(arg0 *http.Response, arg1 error) *MockClientInterfaceMovieDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientInterfaceMovieDetailsCall) Do(f func(context.Context, int32, *client.MovieDetailsParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceMovieDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientInterfaceMovieDetailsCall) DoAndReturn(f func(context.Context, int32, *client.MovieDetailsParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceMovieDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SearchMulti mocks base method.
func (m *MockClientInterface) SearchMulti(ctx context.Context, params *client.SearchMultiParams, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchMulti", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMulti indicates an expected call of SearchMulti.
func (mr *MockClientInterfaceMockRecorder) SearchMulti(ctx, params any, reqEditors ...any) *MockClientInterfaceSearchMultiCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMulti", reflect.TypeOf((*MockClientInterface)(nil).SearchMulti), varargs...)
	return &MockClientInterfaceSearchMultiCall{Call: call}
}

// MockClientInterfaceSearchMultiCall wrap *gomock.Call
type MockClientInterfaceSearchMultiCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientInterfaceSearchMultiCall) Return(arg0 *http.Response, arg1 error) *MockClientInterfaceSearchMultiCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientInterfaceSearchMultiCall) Do(f func(context.Context, *client.SearchMultiParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceSearchMultiCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientInterfaceSearchMultiCall) DoAndReturn(f func(context.Context, *client.SearchMultiParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceSearchMultiCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TvSeriesDetails mocks base method.
func (m *MockClientInterface) TvSeriesDetails(ctx context.Context, seriesId int32, params *client.TvSeriesDetailsParams, reqEditors ...client.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, seriesId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TvSeriesDetails", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TvSeriesDetails indicates an expected call of TvSeriesDetails.
func (mr *MockClientInterfaceMockRecorder) TvSeriesDetails(ctx, seriesId, params any, reqEditors ...any) *MockClientInterfaceTvSeriesDetailsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, seriesId, params}, reqEditors...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TvSeriesDetails", reflect.TypeOf((*MockClientInterface)(nil).TvSeriesDetails), varargs...)
	return &MockClientInterfaceTvSeriesDetailsCall{Call: call}
}

// MockClientInterfaceTvSeriesDetailsCall wrap *gomock.Call
type MockClientInterfaceTvSeriesDetailsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientInterfaceTvSeriesDetailsCall) Return(arg0 *http.Response, arg1 error) *MockClientInterfaceTvSeriesDetailsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientInterfaceTvSeriesDetailsCall) Do(f func(context.Context, int32, *client.TvSeriesDetailsParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceTvSeriesDetailsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientInterfaceTvSeriesDetailsCall) DoAndReturn(f func(context.Context, int32, *client.TvSeriesDetailsParams, ...client.RequestEditorFn) (*http.Response, error)) *MockClientInterfaceTvSeriesDetailsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
