// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/extractor/weighted (interfaces: Scores)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/extractor/weighted/mocks/scores.go github.com/stiflerGit/moviehat/internal/extractor/weighted Scores
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScores is a mock of Scores interface.
type MockScores struct {
	ctrl     *gomock.Controller
	recorder *MockScoresMockRecorder
	isgomock struct{}
}

// MockScoresMockRecorder is the mock recorder for MockScores.
type MockScoresMockRecorder struct {
	mock *MockScores
}

// NewMockScores creates a new mock instance.
func NewMockScores(ctrl *gomock.Controller) *MockScores {
	mock := &MockScores{ctrl: ctrl}
	mock.recorder = &MockScoresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScores) EXPECT() *MockScoresMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockScores) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockScoresMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockScores)(nil).Name))
}

// Scores mocks base method.
func (m *MockScores) Scores(ctx context.Context, userIDs []string) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scores", ctx, userIDs)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scores indicates an expected call of Scores.
func (mr *MockScoresMockRecorder) Scores(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scores", reflect.TypeOf((*MockScores)(nil).Scores), ctx, userIDs)
}
