// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stiflerGit/moviehat/internal/extractor/fair_share/persistence (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/store.go . Store
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	persistence "github.com/stiflerGit/moviehat/internal/extractor/fair_share/persistence"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// IncreaseUserScore mocks base method.
func (m *MockStore) IncreaseUserScore(ctx context.Context, arg persistence.IncreaseUserScoreArg) (persistence.IncreaseUserScoreRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseUserScore", ctx, arg)
	ret0, _ := ret[0].(persistence.IncreaseUserScoreRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncreaseUserScore indicates an expected call of IncreaseUserScore.
func (mr *MockStoreMockRecorder) IncreaseUserScore(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseUserScore", reflect.TypeOf((*MockStore)(nil).IncreaseUserScore), ctx, arg)
}

// ListUsersScores mocks base method.
func (m *MockStore) ListUsersScores(ctx context.Context, arg persistence.ListUsersScoresArg) (persistence.ListUsersScoresRet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsersScores", ctx, arg)
	ret0, _ := ret[0].(persistence.ListUsersScoresRet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsersScores indicates an expected call of ListUsersScores.
func (mr *MockStoreMockRecorder) ListUsersScores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsersScores", reflect.TypeOf((*MockStore)(nil).ListUsersScores), ctx, arg)
}

// WithTx mocks base method.
func (m *MockStore) WithTx(ctx context.Context, fn func(context.Context, persistence.Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockStoreMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockStore)(nil).WithTx), ctx, fn)
}
