syntax = "proto3";

package gateway.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

message CreateInvitationRequest {}

message CreateInvitationResponse {
  string invitation_token = 1;
  string invitation_url = 2;
  google.protobuf.Timestamp expires_at = 3;
  int32 max_uses = 4;
}

message SignUpRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string password = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 8,
    (buf.validate.field).string.max_len = 72
  ];
  string invitation_token = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message SignUpResponse {
  string token = 1;
}

message SignInRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  string password = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 8,
    (buf.validate.field).string.max_len = 72
  ];
}

message SignInResponse {
  string token = 1;
}

message SignOutRequest {}

message SignOutResponse {}

message User {
  string id = 1;
  string name = 2;
}

message ListUsersRequest {
  // TODO: add pagination
}

message ListUsersResponse {
  repeated User users = 1;
}

message UpdateUserRequest {
  string name = 1 [
    (buf.validate.field).string.min_len = 1,
    (buf.validate.field).string.max_len = 255
  ];
}

message UpdateUserResponse {
  User user = 1;
}

message DeleteUserRequest {}

message DeleteUserResponse {
  User user = 1;
}

message CreateSessionRequest {}

message CreateSessionResponse {
  Session session = 1;
}

message Session {
  string id = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp closed_at = 3;
  repeated User participants = 4;
  User winner = 5;
}

message ListSessionsRequest {}

message ListSessionsResponse {
  repeated Session sessions = 1;
}

message GetSessionRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message GetSessionResponse {
  Session session = 1;
}

message EndSessionRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message EndSessionResponse {
  User winner = 1;
}

message SetSessionMovieRequest {
  string session_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
  string movie_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message SetSessionMovieResponse {}

message GetSessionProbabilitiesRequest {
  string session_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message GetSessionProbabilitiesResponse {
  message ParticipantProbabilities {
    string user_id = 1;
    double probability = 2;
  }
  repeated ParticipantProbabilities participants_probabilities = 1;
}

message DeleteSessionRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message DeleteSessionResponse {
  Session session = 1;
}

message AddParticipantRequest {
  string session_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message AddParticipantResponse {}

message RemoveParticipantRequest {
  string session_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
  string user_id = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message RemoveParticipantResponse {}

message ListParticipantsRequest {
  string session_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message ListParticipantsResponse {
  repeated User participants = 1;
}

message AddUserMovieRequest {
  string movie_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
  string note = 2;
}

message Movie {
  string id = 1;
  string title = 2;
  google.protobuf.Timestamp release_date = 3;
  string poster_path = 4;
}

message AddUserMovieResponse {
  Movie movie = 1;
}

message ListUserMoviesRequest {
  string user_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message ListUserMoviesResponse {
  message MovieStatus {
    enum Status {
      STATUS_UNSPECIFIED = 0;
      STATUS_PENDING = 1;
      STATUS_WATCHED = 2;
    }

    Movie movie = 1;
    Status status = 2;
  }

  repeated MovieStatus movies = 1;
}

message DeleteUserMovieRequest {
  string id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.min_len = 1
  ];
}

message DeleteUserMovieResponse {}

message SearchMovieRequest {
  string query = 1;

  // TODO: decide limits here
  // The maximum number of items to return. The service may return fewer than
  // this value.
  // If unspecified, at most X items will be returned.
  // The maximum value is Y; values above Y will be coerced to Y.
  int32 page_size = 2;

  // A page token, received from a previous call.
  // Provide this to retrieve the subsequent page.
  //
  // When paginating, all other parameters must match
  // the call that provided the page token.
  string page_token = 3;
}

message SearchMovieResponse {
  message Result {
    string id = 1;
    string title = 2;
    google.protobuf.Timestamp release_date = 3;
    string poster_path = 4;
  }

  repeated Result results = 8;

  // A token that can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
}

service GatewayService {
  rpc CreateInvitation(CreateInvitationRequest) returns (CreateInvitationResponse);
  rpc SignUp(SignUpRequest) returns (SignUpResponse);
  rpc SignIn(SignInRequest) returns (SignInResponse);
  rpc SignOut(SignOutRequest) returns (SignOutResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
  rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
  rpc CreateSession(CreateSessionRequest) returns (CreateSessionResponse);
  rpc ListSessions(ListSessionsRequest) returns (ListSessionsResponse);
  rpc GetSession(GetSessionRequest) returns (GetSessionResponse);
  rpc EndSession(EndSessionRequest) returns (EndSessionResponse);
  rpc SetSessionMovie(SetSessionMovieRequest) returns (SetSessionMovieResponse);
  rpc GetSessionProbabilities(GetSessionProbabilitiesRequest) returns (GetSessionProbabilitiesResponse);
  rpc DeleteSession(DeleteSessionRequest) returns (DeleteSessionResponse);
  rpc AddParticipant(AddParticipantRequest) returns (AddParticipantResponse);
  rpc RemoveParticipant(RemoveParticipantRequest) returns (RemoveParticipantResponse);
  rpc ListParticipants(ListParticipantsRequest) returns (ListParticipantsResponse);
  rpc AddUserMovie(AddUserMovieRequest) returns (AddUserMovieResponse);
  rpc ListUserMovies(ListUserMoviesRequest) returns (ListUserMoviesResponse);
  rpc DeleteUserMovie(DeleteUserMovieRequest) returns (DeleteUserMovieResponse);
  rpc SearchMovie(SearchMovieRequest) returns (SearchMovieResponse);
}
